<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Concurrency - onRejected dengan Catch Method</title>
  </head>
  <body>
    <script>
      const stock = {
        coffeeBeans: 250,
        water: 1000,
      };

      const checkStock = () => {
        return new Promise((resolve, reject) => {
          if (stock.coffeeBeans >= 16 && stock.water >= 250) {
            resolve("Stok cukup. Bisa membuat kopi");
          } else {
            reject("Stok tidak cukup");
          }
        });
      };

      const handleSuccess = (resolvedValue) => {
        console.log(resolvedValue);
      };

      const handleFailure = (rejectionReason) => {
        console.log(rejectionReason);
      };

      checkStock().then(handleSuccess).catch(handleFailure);
    </script>
  </body>
</html>
